spring:
  application:
    name: nexum
  datasource:
    url: jdbc:postgresql://localhost:5432/nexum
    username: postgres
    password: Tr9a-3ml4#
  jpa:
    hibernate:
      ddl-auto: validate
server:
  error:
    include-message: always
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
jwt:
  public:
    key: classpath:authz.pub
  private:
    key: classpath:authz.pem